### ISSUE TITLE
But how to add it to webthings-gateway?

### ISSUE THREAD

**Issue by eisengrau** [freaktechnik/Webthingify#10]
Hi There,

I have set up webthings-gateway, as per the description on their GitHub page, however, after I enable your app on the phone, on port 8088, the gateway is not able to 'find' it, even if I add the URL with the phone's IP manually. The phone and gateway are on the same sub-net, they can ping each other. Is there anything else special to set up on android, maybe root (already have)? Or a special plugin or add-on needs to be installed on the gateway?

Thank you,

**Comment by freaktechnik** [comment]
That should be everything, however it is possible that a recent update to the gateway has broken the app compatibility, since the latest published version isn't running against the latest webthing library.

**Comment by eisengrau** [comment]
Hello,

Thank you for your quick answer! Yes, that might as well be the case, as I don't have any special config, eg. my wired network can 'reach' my wireless network, as both of them are on the same subnet, there are no special firewalls running on the server where the gateway is hosted, nor on my android devices. As a matter of fact I am using LineageOS on my 'lab' android mobiles, which are rooted, have no gapps, and installed webthingify trough f-droid by allowing 'incompatible' apps.

Thanks,

**Comment by eisengrau** [comment]
Issue related to  #11
